services:
  - type: worker
    name: telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python eba.py
    envVars:
      - key: BOT_TOKEN
        value: 8365880779:AAGuUXsmYdAgumO51qBCyvlTt5nbKhyjFJ8
      - key: FOLDER_ID
        value: b1gm9t0blhv6mioaomgd
      - key: API_KEY
        value: AQVNwvF7BG-GT0rF5FvTbMw9rPlWhxC0xiriMVAa
